@file:Suppress("SpellCheckingInspection")

package moe.matsuri.nb4a.blocklist

import java.util.Locale

/**
 * Человекочитаемые названия для пакетов из [AccreditedBlocklist.defaults].
 * Используются, когда приложение не установлено и `PackageManager` не может
 * дать label. Два словаря: EN и RU. Вызов [resolve] автоматически выбирает
 * по текущей локали.
 */
object AccreditedNames {

    fun resolve(pkg: String): String {
        val lang = Locale.getDefault().language
        val map = if (lang == "ru") namesRu else namesEn
        return map[pkg] ?: pkg
    }

    private val namesEn: Map<String, String> = mapOf(
        // Fintech / neobanks
        "ru.ozon.bank" to "Ozon Bank",
        "ru.wildberries.bank" to "Wildberries Bank",
        "ru.yandex.bank" to "Yandex Bank",
        "ru.sberbank.investor" to "Sber Investor",
        "ru.sberbank.broker" to "Sber Broker",
        "ru.sber.insurance" to "Sber Insurance",
        "ru.sber.leasing" to "Sber Leasing",
        // Investment / trading
        "ru.finam.trade" to "Finam Trade",
        "ru.bcs.broker" to "BCS Broker",
        "ru.openbroker" to "Otkritie Broker",
        "ru.vtb.investments" to "VTB Investments",
        "ru.tinkoff.invest.beta" to "Tinkoff Invest (Beta)",
        "ru.alfa.invest" to "Alfa Investments",
        // Banks (regional)
        "ru.uralsib.mobile" to "Uralsib Bank",
        "ru.absolutbank" to "Absolut Bank",
        "ru.ubrr.mobile" to "UBRIR Bank",
        "ru.tatfondbank" to "Tatfondbank",
        "ru.centerinvest.mobile" to "Center-Invest",
        "ru.lockobank" to "Locko Bank",
        "ru.genbank.mobile" to "Genbank",
        "ru.sdm.mobile" to "SDM Bank",
        // Digital / SME banks
        "ru.delobank" to "Delo Bank",
        "ru.tochka.business" to "Tochka Bank",
        "ru.modulbank.business" to "Modulbank",
        "ru.sfera.bank" to "Sfera Bank",
        // Payment / wallets
        "ru.paykeeper" to "PayKeeper",
        "ru.cloudpayments.app" to "CloudPayments",
        "ru.paylate" to "Paylate",
        "ru.kassa.app" to "Yandex Kassa",
        "ru.uniteller" to "Uniteller",
        // MTS ecosystem
        "ru.mts.mymts" to "My MTS",
        "ru.mts.android.apps.tracker" to "MTS Tracker",
        "ru.mts.android.apps.coordinator" to "MTS Coordinator",
        "ru.mts.link" to "MTS Link",
        "ru.mts.urent" to "MTS Urent",
        "ru.mts.music" to "MTS Music",
        "ru.mts.kion" to "KION",
        "ru.mts.store" to "MTS AppBazar",
        "ru.mts.tv" to "MTS TV",
        "ru.mts.pay" to "MTS Pay",
        "ru.mts.cloud" to "MTS Cloud",
        "ru.mts.id" to "MTS ID",
        "ru.mts.market" to "MTS Market",
        "ru.mts.shop" to "MTS Shop",
        // Beeline
        "ru.beeline.mykabinet" to "My Beeline",
        "ru.beeline.pay" to "Beeline Pay",
        "ru.beeline.music" to "Beeline Music",
        "ru.beeline.tv" to "Beeline TV",
        "ru.beeline.cloud" to "Beeline Cloud",
        "ru.beeline.home" to "Beeline Home",
        // MegaFon
        "ru.megafon.lk" to "MegaFon",
        "ru.megafon.app" to "MegaFon App",
        "ru.megafon.pay" to "MegaFon Pay",
        "ru.megafon.music" to "MegaFon Music",
        "ru.megafon.tv" to "MegaFon TV",
        "ru.megafon.cloud" to "MegaFon Cloud",
        "ru.megafon.business" to "MegaFon Business",
        "ru.megafon.veon" to "MegaFon VEON",
        // Yota
        "ru.yota.app" to "Yota",
        "ru.yota.lk" to "Yota Account",
        "ru.yota.selfcare" to "Yota Selfcare",
        "ru.yota.business" to "Yota Business",
        // VK Play / gaming
        "com.my.mygamesapp" to "VK Play",
        "com.vk.vkplay" to "VK Play (alt)",
        "com.vkontakte.live" to "VK Live",
        "com.vk.live" to "VK Live (alt)",
        "ru.vk.live" to "VK Live (RU)",
        "com.my.games.app" to "MY.GAMES",
        "com.my.games.launcher" to "MY.GAMES Launcher",
        "com.my.games.store" to "MY.GAMES Store",
        "com.my.games.hub" to "MY.GAMES Hub",
        // VK ecosystem (rare)
        "com.vkontakte.workspaces" to "VK Workspaces",
        "com.vkontakte.workspace" to "VK Workspace",
        "com.vkontakte.services" to "VK Services",
        "com.vkontakte.admin" to "VK Admin (old)",
        "com.vkontakte.ads" to "VK Ads (old)",
        "com.vkontakte.analytics" to "VK Analytics",
        "com.vkontakte.store" to "VK Store",
        // VK video
        "com.vk.video.beta" to "VK Video (Beta)",
        "com.vkontakte.video" to "VK Video (old)",
        "ru.vk.video.player" to "VK Video Player",
        // VK ID
        "com.vk.id" to "VK ID",
        "com.vkontakte.account" to "VK Account",
        "ru.vk.passport" to "VK Passport",
        // Yandex (internal)
        "ru.yandex.browser.dev" to "Yandex Browser (Dev)",
        "ru.yandex.browser.alpha" to "Yandex Browser (Alpha)",
        "ru.yandex.search" to "Yandex Search",
        "ru.yandex.services" to "Yandex Services",
        "ru.yandex.superapp" to "Yandex Superapp",
        "ru.yandex.mobile" to "Yandex Mobile",
        "ru.yandex.partner" to "Yandex Partner",
        "ru.yandex.yango" to "Yango",
        "ru.yandex.ubercab" to "Yandex Uber",
        "ru.yandex.uber" to "Yandex Uber (alt)",
        "ru.yandex.courier" to "Yandex Courier",
        // Yandex experimental
        "ru.yandex.food" to "Yandex Food",
        "ru.yandex.shop" to "Yandex Shop",
        "ru.yandex.client" to "Yandex Client",
        "ru.yandex.mobile.exp" to "Yandex Mobile (Exp)",
        // Sber ecosystem (hidden)
        "ru.sberbank.sdk" to "Sber SDK",
        "ru.sberbank.platform" to "Sber Platform",
        "ru.sberbank.id" to "Sber ID",
        "ru.sberbank.auth" to "Sber Auth",
        "ru.sber.devices" to "Sber Devices",
        "ru.sber.auto" to "Sber Auto",
        "ru.sber.health" to "Sber Health",
        "ru.sber.education" to "Sber Education",
        // Rostelecom
        "ru.rt.video" to "Rostelecom Video",
        "ru.rt.portal" to "Rostelecom Portal",
        "ru.rt.service" to "Rostelecom Service",
        "ru.rt.client" to "Rostelecom Client",
        "ru.rt.cloud" to "Rostelecom Cloud",
        "ru.rt.tv" to "Rostelecom TV",
        // Tele2
        "ru.tele2.market" to "Tele2 Market",
        "ru.tele2.pay" to "Tele2 Pay",
        "ru.tele2.tv" to "Tele2 TV",
        // Mail / VK Tech
        "ru.mail.workspace" to "VK WorkSpace",
        "ru.mail.team" to "VK Teams (Mail)",
        "ru.mail.video" to "VK Video (Mail)",
        "ru.mail.biz.video" to "VK WorkVideo",
        "ru.mail.biz.chat" to "VK WorkChat",
        "ru.mail.biz.mail" to "VK WorkMail",
        "ru.mail.biz.calendar" to "VK WorkCalendar",
        // Rambler
        "ru.rambler.video" to "Rambler Video",
        "ru.rambler.weather" to "Rambler Weather",
        "ru.rambler.horoscope" to "Rambler Horoscope",
        "ru.rambler.news" to "Rambler News",
        "ru.rambler.mail" to "Rambler Mail",
        "ru.rambler.games" to "Rambler Games",
        // Streaming
        "ru.more.tv" to "More.tv",
        "ru.start.ru" to "Start",
        "ru.premier.one" to "Premier",
        "ru.kion.android" to "KION",
        "ru.wink.rt" to "Wink",
        // Gaming platforms
        "ru.vk.play" to "VK Play (RU)",
        "ru.my.games" to "MY.GAMES (RU)",
        "com.my.gamestore" to "MY.GAMES Store (alt)",
        "com.my.games.platform" to "MY.GAMES Platform",
        // Cloud / identity / SDK
        "ru.yandex.oauth" to "Yandex OAuth",
        "ru.vk.oauth" to "VK OAuth",
        "ru.sber.oauth" to "Sber OAuth",
        "ru.mail.oauth" to "Mail.ru OAuth",
        "com.vk.auth" to "VK Auth",
        "com.yandex.auth" to "Yandex Auth",
        // Yandex extra
        "ru.yandex.browser.beta" to "Yandex Browser (Beta)",
        "ru.yandex.music.beta" to "Yandex Music (Beta)",
        "ru.yandex.maps.beta" to "Yandex Maps (Beta)",
        "ru.yandex.disk.beta" to "Yandex Disk (Beta)",
        // VK extra
        "com.vk.admin" to "VK Admin",
        "com.vk.ads" to "VK Ads",
        "com.vk.team" to "VK Teams",
        // Sber
        "ru.sberbank.sberpay" to "SberPay",
        "ru.sberbank.sbermarket" to "SberMarket",
        "ru.sberbank.spasibo" to "SberSpasibo",
        "ru.sberbank.onlineassistant" to "Sber Assistant",
        "ru.sberbank.telemed" to "Sber Health",
        "ru.sberdevices.salute" to "Sber Salute",
        // Tinkoff
        "ru.tinkoff.invest" to "Tinkoff Investments",
        "ru.tinkoff.business" to "Tinkoff Business",
        "ru.tinkoff.accounting" to "Tinkoff Accounting",
        // Alfa
        "ru.alfabank.mobile.business" to "Alfa-Bank Business",
        "ru.alfabank.alfainvest" to "Alfa Investments",
        // VTB
        "ru.vtb.invest" to "VTB Investments",
        "ru.vtb.business" to "VTB Business",
        // Fintech
        "ru.payberry.app" to "PayBerry",
        "ru.paymaster.app" to "PayMaster",
        "ru.robokassa.app" to "RoboKassa",
        // Marketplaces
        "ru.kazanexpress.android" to "KazanExpress",
        "ru.sima.land" to "Sima-Land",
        "ru.kupivip" to "KupiVIP",
        "ru.hoff.app" to "Hoff",
        "ru.petrovich.app" to "Petrovich",
        "ru.leroymerlin.android" to "Leroy Merlin",
        "ru.obi.app" to "OBI",
        "ru.globus.app" to "Globus",
        "ru.metro.ccc" to "METRO",
        "ru.auchan.app" to "Auchan",
        "ru.okmarket.app" to "OK Market",
        // Food
        "ru.deliveryclub.app" to "Delivery Club",
        "ru.pizzahut.android" to "Pizza Hut",
        "ru.dodo.pizza" to "Dodo Pizza",
        "ru.tanuki.app" to "Tanuki",
        "ru.kfc.mobile" to "KFC",
        "ru.burgerking" to "Burger King",
        "ru.vkusnoitochka.app" to "Vkusno i Tochka",
        // Pharma
        "ru.eapteka.app" to "Eapteka",
        "ru.rigla.app" to "Rigla",
        "ru.asna.app" to "ASNA",
        "ru.medsi" to "Medsi",
        "ru.invitro.app" to "Invitro",
        "ru.gemotest.app" to "Gemotest",
        // Transport
        "ru.aeroexpress" to "Aeroexpress",
        "ru.mosgortrans" to "Mosgortrans",
        "ru.troika.app" to "Troika",
        "ru.rzd.cargo" to "RZD Cargo",
        "ru.blablacar" to "BlaBlaCar",
        "ru.poputi.app" to "Poputi",
        // Taxi
        "com.citymobil" to "Citymobil",
        "ru.drivee" to "inDrive",
        "ru.yandex.scooters" to "Yandex Scooters",
        // Logistics
        "ru.dpdonline" to "DPD",
        "ru.dellin" to "Delovye Linii",
        "ru.baikalservice" to "Baikal Service",
        "ru.pecom.app" to "PEK",
        // Streaming
        "ru.ntvplus.app" to "NTV+",
        "ru.tricolor.app" to "Tricolor TV",
        "ru.tvzavr" to "Tvzavr",
        "ru.amediateka" to "Amediateka",
        // Work / SaaS
        "ru.bitrix24.app" to "Bitrix24",
        "ru.amocrm.app" to "amoCRM",
        "ru.megaplan.app" to "Megaplan",
        "ru.yclients.mobile" to "YCLIENTS",
        "ru.docsvision" to "Docsvision",
        "ru.elma.app" to "ELMA",
        // Education
        "ru.skillbox.app" to "Skillbox",
        "ru.geekbrains.app" to "GeekBrains",
        "ru.skyeng.student" to "Skyeng Student",
        "ru.skyeng.teacher" to "Skyeng Teacher",
        "ru.foxford.app" to "Foxford",
        "ru.netology.app" to "Netology",
        // Jobs
        "ru.hh.android" to "HeadHunter",
        "ru.superjob.app" to "SuperJob",
        "ru.zarplata.app" to "Zarplata.ru",
        "ru.youdo.app" to "YouDo",
        // Travel
        "ru.tutu" to "Tutu.ru",
        "ru.onetwotrip" to "OneTwoTrip",
        "ru.travelata.app" to "Travelata",
        "ru.sletat.app" to "Sletat.ru",
        "ru.ostrovok.app" to "Ostrovok",
        // Insurance
        "ru.ingos.mobile" to "Ingosstrakh",
        "ru.alfains.mobile" to "Alfa Insurance",
        "ru.renins.app" to "Renaissance Insurance",
        "ru.sogaz.app" to "SOGAZ",
        // Smart home
        "ru.yandex.iot" to "Yandex Smart Home",
        "ru.sber.smart.home" to "Sber Smart Home",
        "ru.rostelecom.smarthome" to "Rostelecom Smart Home",
        // Government
        "ru.pfr.app" to "PFR",
        "ru.gibdd.app" to "GIBDD",
        "ru.mos.transport" to "Moscow Transport",
        "ru.mos.culture" to "Moscow Culture",
        "ru.mos.school" to "Moscow School",
        "ru.mos.dnevnik" to "Moscow Diary",
        // Cloud
        "ru.cloud.mailru" to "Mail.ru Cloud",
        "ru.selectel.mobile" to "Selectel",
        "ru.reg.ru.app" to "REG.RU",
        // Security
        "com.kaspersky.kasperskyinternetsecurity" to "Kaspersky Internet Security",
        "com.kaspersky.passwordmanager" to "Kaspersky Password Manager",
        "ru.drweb" to "Dr.Web",
        "com.eset.mobile.security.russia" to "ESET Mobile Security",
        // App stores
        "ru.rustore.client" to "RuStore",
        "com.nashstore" to "NashStore",
        // Grocery / retail
        "ru.pyaterochka.app" to "Pyaterochka",
        "com.semerochka" to "Semerochka",
        "ru.x5.retailgroup.x5bonus" to "X5 Club",
        "com.avoska.app" to "Avoska",
        "ru.chizhik.app" to "Chizhik",
        "ru.perekrestok.app" to "Perekrestok",
        "ru.magnit.app" to "Magnit",
        "ru.lenta.app" to "Lenta",
        "ru.vprok.app" to "Vprok",
        "ru.utkonos.app" to "Utkonos",
        "ru.samokat.app" to "Samokat",
        "ru.sbermarket" to "SberMarket",
        "ru.torgservis.svetofor" to "Svetofor",
        // DIY
        "ru.maxidom.app" to "Maxidom",
        "ru.vseinstrumenti.app" to "VseInstrumenti.ru",
        "ru.castorama.app" to "Castorama",
        // Banks (major)
        "ru.raiffeisen.mobile" to "Raiffeisen Bank",
        "ru.rosbank.android" to "Rosbank",
        "ru.gazprombank.android.mobilebank" to "Gazprombank",
        "ru.psbank.mobile" to "Promsvyazbank",
        "ru.akbars.mobile" to "Ak Bars Bank",
        // Yandex (core)
        "ru.yandex.searchplugin" to "Yandex",
        "ru.yandex.browser" to "Yandex Browser",
        "ru.yandex.maps" to "Yandex Maps",
        "ru.yandex.metro" to "Yandex Metro",
        "ru.yandex.taxi" to "Yandex Go",
        "ru.yandex.eda" to "Yandex Food",
        "ru.yandex.lavka" to "Yandex Lavka",
        // Social
        "com.vkontakte.android" to "VK",
        "ru.ok.android" to "Odnoklassniki",
        "ru.mail.mailapp" to "Mail.ru",
        // Telecom
        "ru.mts" to "MTS",
        "ru.megafon.mlk" to "MegaFon",
        "ru.beeline.services" to "Beeline",
        "ru.tele2.mytele2" to "Tele2",
        // Government / Classifieds
        "ru.gosuslugi.android" to "Gosuslugi",
        "ru.avito.android" to "Avito",
        // RKS additions
        "ru.sberbank.android" to "Sberbank Online",
        "ru.tinkoff.bank" to "T-Bank (Tinkoff)",
        "com.vk.video" to "VK Video",
        "com.wildberries.ru" to "Wildberries",
        "ru.kinopoisk" to "Kinopoisk",
        "ru.ozon.app" to "Ozon",
        "ru.dublgis.dgismobile" to "2GIS",
        "com.vkontakte.music" to "VK Music"
    )

    private val namesRu: Map<String, String> = mapOf(
        // Fintech / neobanks
        "ru.ozon.bank" to "Озон Банк",
        "ru.wildberries.bank" to "Вайлдберриз Банк",
        "ru.yandex.bank" to "Яндекс Банк",
        "ru.sberbank.investor" to "Сбер Инвестор",
        "ru.sberbank.broker" to "Сбер Брокер",
        "ru.sber.insurance" to "СберСтрахование",
        "ru.sber.leasing" to "Сбер Лизинг",
        // Investment / trading
        "ru.finam.trade" to "Финам Трейд",
        "ru.bcs.broker" to "БКС Брокер",
        "ru.openbroker" to "Открытие Брокер",
        "ru.vtb.investments" to "ВТБ Инвестиции",
        "ru.tinkoff.invest.beta" to "Тинькофф Инвестиции (бета)",
        "ru.alfa.invest" to "Альфа-Инвестиции",
        // Banks (regional)
        "ru.uralsib.mobile" to "Уралсиб",
        "ru.absolutbank" to "Абсолют Банк",
        "ru.ubrr.mobile" to "УБРИР",
        "ru.tatfondbank" to "Татфондбанк",
        "ru.centerinvest.mobile" to "Центр-инвест",
        "ru.lockobank" to "Локо-Банк",
        "ru.genbank.mobile" to "Генбанк",
        "ru.sdm.mobile" to "СДМ Банк",
        // Digital / SME banks
        "ru.delobank" to "Делобанк",
        "ru.tochka.business" to "Точка Банк",
        "ru.modulbank.business" to "Модульбанк",
        "ru.sfera.bank" to "Сфера Банк",
        // Payment / wallets
        "ru.paykeeper" to "PayKeeper",
        "ru.cloudpayments.app" to "CloudPayments",
        "ru.paylate" to "Paylate",
        "ru.kassa.app" to "ЮKassa",
        "ru.uniteller" to "Юнителлер",
        // MTS ecosystem
        "ru.mts.mymts" to "Мой МТС",
        "ru.mts.android.apps.tracker" to "МТС Трекер",
        "ru.mts.android.apps.coordinator" to "МТС Координатор",
        "ru.mts.link" to "МТС Линк",
        "ru.mts.urent" to "МТС Юрент",
        "ru.mts.music" to "МТС Музыка",
        "ru.mts.kion" to "KION",
        "ru.mts.store" to "МТС AppBazar",
        "ru.mts.tv" to "МТС ТВ",
        "ru.mts.pay" to "МТС Pay",
        "ru.mts.cloud" to "МТС Облако",
        "ru.mts.id" to "МТС ID",
        "ru.mts.market" to "МТС Маркет",
        "ru.mts.shop" to "МТС Магазин",
        // Beeline
        "ru.beeline.mykabinet" to "Мой Билайн",
        "ru.beeline.pay" to "Билайн Pay",
        "ru.beeline.music" to "Билайн Музыка",
        "ru.beeline.tv" to "Билайн ТВ",
        "ru.beeline.cloud" to "Билайн Облако",
        "ru.beeline.home" to "Билайн Дом",
        // MegaFon
        "ru.megafon.lk" to "МегаФон",
        "ru.megafon.app" to "МегаФон",
        "ru.megafon.pay" to "МегаФон Pay",
        "ru.megafon.music" to "МегаФон Музыка",
        "ru.megafon.tv" to "МегаФон ТВ",
        "ru.megafon.cloud" to "МегаФон Облако",
        "ru.megafon.business" to "МегаФон Бизнес",
        "ru.megafon.veon" to "МегаФон VEON",
        // Yota
        "ru.yota.app" to "Yota",
        "ru.yota.lk" to "Yota Кабинет",
        "ru.yota.selfcare" to "Yota Самообслуживание",
        "ru.yota.business" to "Yota Бизнес",
        // VK Play / gaming
        "com.my.mygamesapp" to "VK Play",
        "com.vk.vkplay" to "VK Play (альт)",
        "com.vkontakte.live" to "VK Live",
        "com.vk.live" to "VK Live (альт)",
        "ru.vk.live" to "VK Live (RU)",
        "com.my.games.app" to "MY.GAMES",
        "com.my.games.launcher" to "MY.GAMES Лаунчер",
        "com.my.games.store" to "MY.GAMES Store",
        "com.my.games.hub" to "MY.GAMES Hub",
        // VK ecosystem (rare)
        "com.vkontakte.workspaces" to "VK Workspaces",
        "com.vkontakte.workspace" to "VK Workspace",
        "com.vkontakte.services" to "VK Сервисы",
        "com.vkontakte.admin" to "Админ ВКонтакте (старый)",
        "com.vkontakte.ads" to "VK Реклама (старый)",
        "com.vkontakte.analytics" to "VK Аналитика",
        "com.vkontakte.store" to "VK Store",
        // VK video
        "com.vk.video.beta" to "VK Видео (бета)",
        "com.vkontakte.video" to "VK Видео (старый)",
        "ru.vk.video.player" to "VK Видеоплеер",
        // VK ID
        "com.vk.id" to "VK ID",
        "com.vkontakte.account" to "VK Аккаунт",
        "ru.vk.passport" to "VK Паспорт",
        // Yandex (internal)
        "ru.yandex.browser.dev" to "Яндекс Браузер (Dev)",
        "ru.yandex.browser.alpha" to "Яндекс Браузер (Альфа)",
        "ru.yandex.search" to "Яндекс Поиск",
        "ru.yandex.services" to "Яндекс Сервисы",
        "ru.yandex.superapp" to "Яндекс Суперприложение",
        "ru.yandex.mobile" to "Яндекс Мобайл",
        "ru.yandex.partner" to "Яндекс Партнёр",
        "ru.yandex.yango" to "Yango",
        "ru.yandex.ubercab" to "Яндекс Uber",
        "ru.yandex.uber" to "Яндекс Uber (альт)",
        "ru.yandex.courier" to "Яндекс Курьер",
        // Yandex experimental
        "ru.yandex.food" to "Яндекс Еда",
        "ru.yandex.shop" to "Яндекс Магазин",
        "ru.yandex.client" to "Яндекс Клиент",
        "ru.yandex.mobile.exp" to "Яндекс Мобайл (эксп.)",
        // Sber ecosystem (hidden)
        "ru.sberbank.sdk" to "Сбер SDK",
        "ru.sberbank.platform" to "Сбер Платформа",
        "ru.sberbank.id" to "Сбер ID",
        "ru.sberbank.auth" to "Сбер Авторизация",
        "ru.sber.devices" to "Сбер Устройства",
        "ru.sber.auto" to "Сбер Авто",
        "ru.sber.health" to "СберЗдоровье",
        "ru.sber.education" to "СберОбразование",
        // Rostelecom
        "ru.rt.video" to "Ростелеком Видео",
        "ru.rt.portal" to "Ростелеком Портал",
        "ru.rt.service" to "Ростелеком Сервис",
        "ru.rt.client" to "Ростелеком Клиент",
        "ru.rt.cloud" to "Ростелеком Облако",
        "ru.rt.tv" to "Ростелеком ТВ",
        // Tele2
        "ru.tele2.market" to "Tele2 Маркет",
        "ru.tele2.pay" to "Tele2 Pay",
        "ru.tele2.tv" to "Tele2 ТВ",
        // Mail / VK Tech
        "ru.mail.workspace" to "VK WorkSpace",
        "ru.mail.team" to "VK Тимс (Mail)",
        "ru.mail.video" to "VK Видео (Mail)",
        "ru.mail.biz.video" to "Почта Mail.ru: Видео для бизнеса",
        "ru.mail.biz.chat" to "Почта Mail.ru: Чат для бизнеса",
        "ru.mail.biz.mail" to "Почта Mail.ru для бизнеса",
        "ru.mail.biz.calendar" to "Календарь Mail.ru для бизнеса",
        // Rambler
        "ru.rambler.video" to "Рамблер Видео",
        "ru.rambler.weather" to "Рамблер Погода",
        "ru.rambler.horoscope" to "Рамблер Гороскоп",
        "ru.rambler.news" to "Рамблер Новости",
        "ru.rambler.mail" to "Рамблер Почта",
        "ru.rambler.games" to "Рамблер Игры",
        // Streaming
        "ru.more.tv" to "More.tv",
        "ru.start.ru" to "Start",
        "ru.premier.one" to "Premier",
        "ru.kion.android" to "KION",
        "ru.wink.rt" to "Wink",
        // Gaming
        "ru.vk.play" to "VK Play (RU)",
        "ru.my.games" to "MY.GAMES (RU)",
        "com.my.gamestore" to "MY.GAMES Store (альт)",
        "com.my.games.platform" to "MY.GAMES Платформа",
        // Cloud / identity
        "ru.yandex.oauth" to "Яндекс OAuth",
        "ru.vk.oauth" to "VK OAuth",
        "ru.sber.oauth" to "Сбер OAuth",
        "ru.mail.oauth" to "Mail.ru OAuth",
        "com.vk.auth" to "VK Auth",
        "com.yandex.auth" to "Яндекс Auth",
        // Yandex extra
        "ru.yandex.browser.beta" to "Яндекс Браузер (бета)",
        "ru.yandex.music.beta" to "Яндекс Музыка (бета)",
        "ru.yandex.maps.beta" to "Яндекс Карты (бета)",
        "ru.yandex.disk.beta" to "Яндекс Диск (бета)",
        // VK extra
        "com.vk.admin" to "Админ ВКонтакте",
        "com.vk.ads" to "VK Реклама",
        "com.vk.team" to "VK Тимс",
        // Sber
        "ru.sberbank.sberpay" to "СберПэй",
        "ru.sberbank.sbermarket" to "СберМаркет",
        "ru.sberbank.spasibo" to "СберСпасибо",
        "ru.sberbank.onlineassistant" to "СберАссистент",
        "ru.sberbank.telemed" to "СберЗдоровье",
        "ru.sberdevices.salute" to "Салют (Сбер)",
        // Tinkoff
        "ru.tinkoff.invest" to "Тинькофф Инвестиции",
        "ru.tinkoff.business" to "Тинькофф Бизнес",
        "ru.tinkoff.accounting" to "Тинькофф Бухгалтерия",
        // Alfa
        "ru.alfabank.mobile.business" to "Альфа-Банк Бизнес",
        "ru.alfabank.alfainvest" to "Альфа-Инвестиции",
        // VTB
        "ru.vtb.invest" to "ВТБ Инвестиции",
        "ru.vtb.business" to "ВТБ Бизнес",
        // Fintech
        "ru.payberry.app" to "ПэйБерри",
        "ru.paymaster.app" to "ПэйМастер",
        "ru.robokassa.app" to "Робокасса",
        // Marketplaces
        "ru.kazanexpress.android" to "КазаньЭкспресс",
        "ru.sima.land" to "Сима-ленд",
        "ru.kupivip" to "КупиВИП",
        "ru.hoff.app" to "Хофф",
        "ru.petrovich.app" to "Петрович",
        "ru.leroymerlin.android" to "Леруа Мерлен",
        "ru.obi.app" to "ОБИ",
        "ru.globus.app" to "Глобус",
        "ru.metro.ccc" to "Метро Кэш энд Керри",
        "ru.auchan.app" to "Ашан",
        "ru.okmarket.app" to "ОК Маркет",
        // Food
        "ru.deliveryclub.app" to "Деливери Клаб",
        "ru.pizzahut.android" to "Пицца Хат",
        "ru.dodo.pizza" to "Додо Пицца",
        "ru.tanuki.app" to "Тануки",
        "ru.kfc.mobile" to "КФС",
        "ru.burgerking" to "Бургер Кинг",
        "ru.vkusnoitochka.app" to "Вкусно — и точка",
        // Pharma
        "ru.eapteka.app" to "ЕАптека",
        "ru.rigla.app" to "Ригла",
        "ru.asna.app" to "АСНА",
        "ru.medsi" to "Медси",
        "ru.invitro.app" to "Инвитро",
        "ru.gemotest.app" to "Гемотест",
        // Transport
        "ru.aeroexpress" to "Аэроэкспресс",
        "ru.mosgortrans" to "Мосгортранс",
        "ru.troika.app" to "Тройка",
        "ru.rzd.cargo" to "РЖД Груз",
        "ru.blablacar" to "БлаБлаКар",
        "ru.poputi.app" to "Попутчики",
        // Taxi
        "com.citymobil" to "Ситимобил",
        "ru.drivee" to "инДрайв",
        "ru.yandex.scooters" to "Яндекс Самокаты",
        // Logistics
        "ru.dpdonline" to "ДПД",
        "ru.dellin" to "Деловые Линии",
        "ru.baikalservice" to "Байкал Сервис",
        "ru.pecom.app" to "ПЭК",
        // Streaming
        "ru.ntvplus.app" to "НТВ+",
        "ru.tricolor.app" to "Триколор ТВ",
        "ru.tvzavr" to "ТВзавр",
        "ru.amediateka" to "Амедиатека",
        // Work / SaaS
        "ru.bitrix24.app" to "Битрикс24",
        "ru.amocrm.app" to "амоCRM",
        "ru.megaplan.app" to "Мегаплан",
        "ru.yclients.mobile" to "YCLIENTS",
        "ru.docsvision" to "Докcвижн",
        "ru.elma.app" to "ELMA",
        // Education
        "ru.skillbox.app" to "Скиллбокс",
        "ru.geekbrains.app" to "ГикБрейнс",
        "ru.skyeng.student" to "Skyeng (ученик)",
        "ru.skyeng.teacher" to "Skyeng (преподаватель)",
        "ru.foxford.app" to "Фоксфорд",
        "ru.netology.app" to "Нетология",
        // Jobs
        "ru.hh.android" to "hh.ru",
        "ru.superjob.app" to "СуперДжоб",
        "ru.zarplata.app" to "Зарплата.ру",
        "ru.youdo.app" to "Юду",
        // Travel
        "ru.tutu" to "Туту.ру",
        "ru.onetwotrip" to "Вантутрип",
        "ru.travelata.app" to "Травелата",
        "ru.sletat.app" to "Слетать.ру",
        "ru.ostrovok.app" to "Островок",
        // Insurance
        "ru.ingos.mobile" to "Ингосстрах",
        "ru.alfains.mobile" to "АльфаСтрахование",
        "ru.renins.app" to "Ренессанс Страхование",
        "ru.sogaz.app" to "СОГАЗ",
        // Smart home
        "ru.yandex.iot" to "Умный дом Яндекса",
        "ru.sber.smart.home" to "Умный дом Сбера",
        "ru.rostelecom.smarthome" to "Умный дом Ростелеком",
        // Government
        "ru.pfr.app" to "Пенсионный фонд",
        "ru.gibdd.app" to "ГИБДД",
        "ru.mos.transport" to "Московский транспорт",
        "ru.mos.culture" to "Культура Москвы",
        "ru.mos.school" to "Школа Москвы",
        "ru.mos.dnevnik" to "Электронный дневник Москвы",
        // Cloud
        "ru.cloud.mailru" to "Облако Mail.ru",
        "ru.selectel.mobile" to "Селектел",
        "ru.reg.ru.app" to "Рег.ру",
        // Security
        "com.kaspersky.kasperskyinternetsecurity" to "Kaspersky Интернет Безопасность",
        "com.kaspersky.passwordmanager" to "Менеджер паролей Kaspersky",
        "ru.drweb" to "Доктор Веб",
        "com.eset.mobile.security.russia" to "ESET Мобильная безопасность",
        // Магазины приложений
        "ru.rustore.client" to "РуСтор",
        "com.nashstore" to "НашСтор",
        // Продуктовые сети
        "ru.pyaterochka.app" to "Пятёрочка",
        "com.semerochka" to "Семёрочка",
        "ru.x5.retailgroup.x5bonus" to "X5 Клуб",
        "com.avoska.app" to "Авоська",
        "ru.chizhik.app" to "Чижик",
        "ru.perekrestok.app" to "Перекрёсток",
        "ru.magnit.app" to "Магнит",
        "ru.lenta.app" to "Лента",
        "ru.vprok.app" to "Впрок",
        "ru.utkonos.app" to "Утконос",
        "ru.samokat.app" to "Самокат",
        "ru.sbermarket" to "СберМаркет",
        "ru.torgservis.svetofor" to "Светофор",
        // Стройка / DIY
        "ru.maxidom.app" to "Максидом",
        "ru.vseinstrumenti.app" to "ВсеИнструменты.ру",
        "ru.castorama.app" to "Касторама",
        // Банки (крупные)
        "ru.raiffeisen.mobile" to "Райффайзен Банк",
        "ru.rosbank.android" to "Росбанк",
        "ru.gazprombank.android.mobilebank" to "Газпромбанк",
        "ru.psbank.mobile" to "Промсвязьбанк",
        "ru.akbars.mobile" to "Ак Барс Банк",
        // Яндекс (основные)
        "ru.yandex.searchplugin" to "Яндекс",
        "ru.yandex.browser" to "Яндекс Браузер",
        "ru.yandex.maps" to "Яндекс Карты",
        "ru.yandex.metro" to "Яндекс Метро",
        "ru.yandex.taxi" to "Яндекс Go",
        "ru.yandex.eda" to "Яндекс Еда",
        "ru.yandex.lavka" to "Яндекс Лавка",
        // Соцсети
        "com.vkontakte.android" to "ВКонтакте",
        "ru.ok.android" to "Одноклассники",
        "ru.mail.mailapp" to "Почта Mail.ru",
        // Операторы
        "ru.mts" to "МТС",
        "ru.megafon.mlk" to "МегаФон",
        "ru.beeline.services" to "Билайн",
        "ru.tele2.mytele2" to "Tele2",
        // Госуслуги / Объявления
        "ru.gosuslugi.android" to "Госуслуги",
        "ru.avito.android" to "Авито",
        // RKS
        "ru.sberbank.android" to "Сбербанк Онлайн",
        "ru.tinkoff.bank" to "Т-Банк (Тинькофф)",
        "com.vk.video" to "VK Видео",
        "com.wildberries.ru" to "Вайлдберриз",
        "ru.kinopoisk" to "Кинопоиск",
        "ru.ozon.app" to "Озон",
        "ru.dublgis.dgismobile" to "2ГИС",
        "com.vkontakte.music" to "VK Музыка"
    )
}
